import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      data-theme='winter'
    >
      <body className={inter.className}>
        <NavBar />
        <main className='p-5'>
          {/* To automatically show loading message while navigating through pages we can wrap children in root layout in suspense component. For complex and heavy pages this provide better user experience. This is one way. we can create special loading file in next js */}
          {/* <Suspense fallback={<p>Loading...</p>}>{children}</Suspense> */}
          {children}
        </main>
      </body>
    </html>
  );
}
